{
  "lang_name": "English",
  "lang_flag": "GB",
  "panel_main": "PolyPulse",
  "section_analysis": "Analysis",
  "section_optimization": "Optimization",
  "section_export": "Export",
  "section_validation": "Validation",
  "section_settings": "Settings",
  "section_reports": "Reports",
  "section_score": "Game Ready Score",
  "section_draw_calls": "Performance Analysis",
  "section_last_op": "Last Operation",
  "section_warnings": "Warnings",
  "section_textures": "Textures",
  "section_lod_chain": "LOD Chain",
  "btn_analyze_scene": "Analyze Scene",
  "btn_advanced_scan": "Advanced Scan",
  "btn_game_ready_check": "Game Ready Check",
  "btn_auto_fix_mesh": "Auto Fix Mesh",
  "btn_generate_lods": "Generate Game Ready LODs",
  "btn_generate_lod1": "Generate LOD 1 (50%)",
  "btn_generate_lod2": "Generate LOD 2 (25%)",
  "btn_generate_lod3": "Generate LOD 3 (10%)",
  "btn_smart_decimate": "Smart Decimate",
  "btn_remove_doubles": "Remove Doubles",
  "btn_merge_objects": "Merge Selected Objects",
  "btn_texture_scan": "Texture Scan",
  "btn_export_report": "Export Report",
  "btn_batch_optimize": "Batch Optimize Folder",
  "btn_export_ue5": "Unreal Engine 5",
  "btn_export_unity": "Unity",
  "btn_export_godot": "Godot",
  "lbl_language": "Language",
  "lbl_objects": "Objects",
  "lbl_meshes": "Meshes",
  "lbl_vertices": "Vertices",
  "lbl_edges": "Edges",
  "lbl_polygons": "Polygons",
  "lbl_triangles": "Triangles",
  "lbl_ngons": "Ngons",
  "lbl_materials": "Materials",
  "lbl_textures": "Textures",
  "lbl_uv": "UV Map",
  "lbl_normals": "Normals",
  "lbl_yes": "YES",
  "lbl_no": "NO",
  "lbl_draw_calls": "Estimated Draw Calls",
  "lbl_triangles_count": "Triangles",
  "lbl_recommendation": "Recommendation",
  "lbl_run_advanced": "Run 'Advanced Scan' to get score",
  "lbl_no_textures": "No textures scanned yet",
  "lbl_no_warnings": "No critical issues detected",
  "lbl_invalid_folder": "Invalid folder",
  "lbl_no_blend_files": "No .blend files found in folder",
  "score_poor": "Poor",
  "score_needs_optimization": "Needs Optimization",
  "score_game_ready": "Game Ready",
  "score_excellent": "Excellent",
  "msg_analyzed_scene": "Scene analyzed",
  "msg_advanced_scan_complete": "Advanced scan complete",
  "msg_no_mesh_selected": "No mesh objects selected",
  "msg_no_doubles": "No duplicate vertices found",
  "msg_removed_doubles": "Removed duplicate vertices",
  "msg_merged_objects": "Objects merged",
  "msg_decimate_complete": "Smart decimate complete",
  "msg_auto_fix_complete": "Auto fix complete",
  "msg_lod_chain_complete": "LOD chain generated",
  "msg_lod_complete": "LOD generated",
  "msg_texture_scan_complete": "Texture scan complete",
  "msg_report_saved": "Report saved",
  "msg_batch_complete": "Batch optimization complete",
  "msg_export_complete": "Export complete",
  "msg_export_failed": "Export failed",
  "msg_validation_complete": "Validation complete",
  "msg_blend_not_saved": "Blend file not saved — report in home dir",
  "warn_too_many_polys": "Too many polygons for a game asset",
  "warn_ngons_found": "Found ngons — may cause issues in engine",
  "warn_no_uv": "Missing UV map — required for textures",
  "warn_no_normals": "Missing normals — lighting may break",
  "warn_too_many_materials": "Too many materials — consider atlasing",
  "warn_large_texture": "Texture >4K — downscale recommended",
  "warn_duplicate_verts": "Found duplicate vertices",
  "warn_overlapping_uv": "Found overlapping UV islands",
  "warn_missing_texture": "Material has no textures assigned",
  "popup_objects_processed": "Objects processed",
  "popup_verts_merged": "Vertices merged",
  "popup_polys_before": "Polygons before",
  "popup_polys_after": "Polygons after",
  "popup_optimization": "Optimization",
  "popup_meshes_processed": "Meshes processed",
  "popup_fixed_issues": "Issues fixed",
  "popup_target_ratio": "Target ratio",
  "popup_files_analyzed": "Files analyzed",
  "popup_errors": "Errors",
  "popup_total_objects": "Total objects",
  "popup_total_meshes": "Total meshes",
  "popup_total_materials": "Total materials",
  "popup_total_textures": "Total textures",
  "popup_file": "File",
  "popup_path": "Path",
  "popup_meshes_created": "Meshes created",
  "popup_target_mesh": "Target mesh",
  "popup_position_preserved": "Position preserved",
  "popup_game_score": "Game Score",
  "popup_label": "Label",
  "popup_geometry": "Geometry",
  "popup_textures": "Textures",
  "popup_optimization_score": "Optimization",
  "label_score_geometry": "Geometry",
  "label_score_textures": "Textures",
  "label_score_materials": "Materials",
  "label_score_optimization": "Optimization",
  "rec_combine_materials": "Combine materials to improve performance",
  "rec_ready_ue5": "Asset is ready for Unreal Engine 5",
  "rec_ready_unity": "Asset is ready for Unity",
  "rec_ready_godot": "Asset is ready for Godot",
  "rec_optimize_required": "Optimization required before game engine",
  "rec_heavy_optimization": "Heavy optimization needed — not game-ready",
  "rec_near_ready": "Almost ready — minor tweaks recommended",
  "settings_choose_language": "Choose interface language",
  "validation_geometry": "Geometry",
  "validation_textures": "Textures",
  "validation_materials": "Materials",
  "validation_uv": "UV Map",
  "validation_pass": "PASS",
  "validation_fail": "FAIL",
  "section_asset_prep": "Asset Preparation",
  "section_collider": "Collider Generator",
  "section_uv_atlas": "UV Atlas Generator",
  "section_visual": "Visual Overlay",
  "btn_generate_collider": "Generate Collider",
  "btn_create_uv_atlas": "Create UV Atlas",
  "btn_visual_scan": "Visual Scan",
  "lbl_collider_type": "Collider Type",
  "lbl_visible_render": "Visible in Render",
  "lbl_angle_limit": "Angle Limit",
  "lbl_island_margin": "Island Margin",
  "lbl_merge_materials": "Merge Materials",
  "lbl_legend": "Legend",
  "lbl_red_ngons": "Red = Ngons",
  "lbl_yellow_uv": "Yellow = Missing UV",
  "lbl_blue_dups": "Blue = Dup Verts",
  "msg_collider_generated": "Colliders generated",
  "msg_uv_atlas_created": "UV Atlas created",
  "msg_visual_scan_on": "Visual Scan ON",
  "msg_visual_scan_off": "Visual Scan OFF",
  "popup_collider_type": "Type",
  "popup_collider_created": "Created",
  "popup_collider_failed": "Failed",
  "popup_mats_before": "Materials before",
  "popup_mats_after": "Materials after",
  "popup_uv_islands_before": "UV islands before",
  "popup_uv_islands_after": "UV islands after",
  "popup_ngons_count": "Ngons (red)",
  "popup_missing_uv_count": "Missing UV (yellow)",
  "popup_dup_verts_count": "Dup verts (blue)",
  "popup_overlay_enabled": "Overlay enabled in viewport",
  "popup_click_to_disable": "Click again to disable",
  "collider_box": "Box Collider",
  "collider_sphere": "Sphere Collider",
  "collider_capsule": "Capsule Collider",
  "collider_convex": "Convex Collider",
  "rec_collider_ready": "Colliders ready for UE5 / Unity / Godot",
  "rec_uv_atlas_ready": "UV Atlas ready — single material workflow",
  "subsec_mesh_repair": "Mesh Repair",
  "subsec_engine_presets": "Engine Presets",
  "subsec_textures": "Textures",
  "subsec_reports": "Reports"
}
